#!/bin/bash
#SBATCH --qos=<QOS>
#SBATCH --partition=<PARTITION>
#SBATCH --time=<WALL>
#SBATCH --job-name=<JOBNAME>
#SBATCH --account=<ACCOUNT>
#SBATCH --output=./out.out
#SBATCH --error=./out.err
#SBATCH --exclusive
<EMAILSECTION>

<OMPSECTION>

ulimit -s unlimited
ulimit -v unlimited

# Run the job
srun <CMD>
